name: First Workflow
on: workflow_dispatch # manualy trigger
jobs:
  first-job:
    runs-on: ubuntu-latest
    outputs:
      repo: ${{ steps.docker-repository.outputs.repo }}
      tag: ${{ steps.image-tag.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Show docker-repository
#        run: make docker-repository
        id: docker-repository
        run: echo "repo=$(make docker-repository)" >> $GITHUB_OUTPUT

      - name: Show image-tag
#        run: make docker-image-tag
        id: image-tag
        run: echo "image=$(make docker-image-tag)" >> $GITHUB_OUTPUT
  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: Show variables
        run: |
          echo "Repo: ${{ needs.first-job.outputs.repo }}"
          echo "Tag: ${{ needs.first-job.outputs.tag }}"