name: First Workflow
on: workflow_dispatch # manualy trigger
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Show docker-repository
#        run: make docker-repository
        run: echo "DOCKER_REPOSITORY=$(make docker-repository)" >> $GITHUB_ENV

      - name: Show image-tag
#        run: make docker-image-tag
        run: echo "DOCKER_IMAGE_TAG=$(make image-tag)" >> $GITHUB_ENV
  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: Show variables
        run: |
          echo ${{ env.DOCKER_REPOSITORY }}
          echo ${{ env.DOCKER_IMAGE_TAG }}