name: First Workflow
on: workflow_dispatch # manualy trigger
jobs:
  first-job:
    runs-on: ubuntu-latest
    outputs:
      repo: ${{ steps.docker-repository.outputs.repo }}
      tag: ${{ steps.docker-repository.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create repository data
        id: docker-repository
        run: |
          echo "repo=\"$(make docker-repository)\"" >> $GITHUB_OUTPUT
          echo "image=$(make docker-image-tag)" >> $GITHUB_OUTPUT

  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: Show variables
        run: |
          echo "Repo: ${{ needs.first-job.outputs.repo }}"
          echo "Tag: ${{ needs.first-job.outputs.tag }}"