name: First Workflow
on: workflow_dispatch # manualy trigger
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greating
        run: echo "Hello World!"
      - name: Print goodbye
        run: |
          echo "Done - bye!"
          echo "DOCKER_IMAGE_TAG=$(make print-docker-image-tag)" >> $GITHUB_ENV
          echo "tag: ${DOCKER_IMAGE_TAG}"
          make print-docker-image-tag
      - name: Print env from Makefile
        run: |
          echo ${{ env.DOCKER_IMAGE_TAG }}
          
