name: First Workflow
on:
  push:
    branches-ignore:
      - "master"
      - "release/*"
    tags:
      - "*.*.*"
      - "*.*.*.*"

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Print data
        run: |
          echo "Print if commit push to develop branch:"
          echo ${{ toJSON(github) }}
          echo ${{ github.ref }}
          ${{ github.ref == 'refs/heads/develop' }}
          echo ${{ github.event_name }}
